version: '3.9'

services:
  wp:
    container_name: ${APP_NAME}-wordpress
    build:
      context: ${DOCKER_PATH}
    ports:
      - "${IP}:80:80" # change ip if required
      - "${IP}:443:443"
    volumes:
      - ${DOCKER_PATH}/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${PROJECT_PATH}/${APP_NAME}:/var/www/html # Full wordpress project
      #- ./phpdocker/config/.htaccess:/var/www/html/.htaccess # Modified .htaccess
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG}"
      XDEBUG_CONFIG: "remote_host=${XDEBUG_REMOTE_HOST} idekey=${XDEBUG_IDEKEY} remote_autostart=1 remote_connect_back=0 remote_enable=1 remote_handler=dbgp remote_mode=req remote_port=9009"
    depends_on:
      - db
    networks:
      - wordpress

  wpcli:
    image: wordpress:cli
    container_name: ${APP_NAME}-wpcli
    volumes:
      - ${DOCKER_PATH}/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${PROJECT_PATH}/${APP_NAME}:/var/www/html
    entrypoint: wp
    command: "--info"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp
    networks:
      - wordpress

  pma:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 300M
    ports:
      - "${IP}:8181:80"
    networks:
      - wordpress

  db:
    image: mariadb:10.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: ${APP_NAME}-db
    #platform: linux/amd64 # Apple M1 compatibility
    ports:
      - "${IP}:3306:3306" # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ${DOCKER_PATH}/wp-data:/docker-entrypoint-initdb.d
      - ${DOCKER_PATH}/db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%" # Apple M1 compatibility
    networks:
      - wordpress

volumes:
  db_data:

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
